<<<<<<< HEAD
const articulosDuster = [
  {
    id: 1,
    imagen: './material/imagenes/duster/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 535300,
  },
  {
    id: 2,
    imagen: './material/imagenes/duster/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Cuenta con tapas plásticas para no dañar la carga.',
    precio: 171500,
  },
  {
    id: 3,
    imagen: './material/imagenes/duster/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 230300,
  },
  {
    id: 4,
    imagen: './material/imagenes/duster/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Protege y decora el vehículo.',
    descripcion2: 'Gran resistencia.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 171400,
  },
  {
    id: 5,
    imagen: './material/imagenes/duster/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 67100,
  },
  {
    id: 6,
    imagen: './material/imagenes/duster/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Listo para instalar.',
    descripcion2: 'Bloquea el acceso de herramientas genéricas.',
    descripcion3: 'Bloqueo del malacate de la rueda de auxilio.',
    precio: 23800,
  },
  {
    id: 7,
    imagen: './material/imagenes/duster/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 159000,
  },
  {
    id: 8,
    imagen: './material/imagenes/duster/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 131100,
  },
  {
    id: 9,
    imagen: './material/imagenes/duster/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 174500,
  },
  {
    id: 10,
    imagen: './material/imagenes/duster/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 52900,
  },
  {
    id: 11,
    imagen: './material/imagenes/duster/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 69800,
  },
  {
    id: 12,
    imagen: './material/imagenes/duster/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 71300,
  }
]
const articulosKangoo = [
  {
    id: 1,
    imagen: './material/imagenes/kangoo/1.jpg',
    nombre: 'CANASTO TECHO',
    descripcion1: 'Cubre totalmente el techo.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Peso máximo soportado 90 Kg.',
    precio: 830400,
  },
  {
    id: 2,
    imagen: './material/imagenes/kangoo/2.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 321800,
  },
  {
    id: 3,
    imagen: './material/imagenes/kangoo/3.jpg',
    nombre: 'CAMARA DE RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 131100,
  },
  {
    id: 4,
    imagen: './material/imagenes/kangoo/4.jpg',
    nombre: 'LLANTAS DE ALEACIÓN',
    descripcion1: 'Ancho 15.25 Cm.',
    descripcion2: 'Diámetro de la llanta 15 pulgadas.',
    descripcion3: 'Material Aleación de aluminio.',
    precio: 488500,
  },
  {
    id: 5,
    imagen: './material/imagenes/kangoo/5.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 174500,
  },
  {
    id: 6,
    imagen: './material/imagenes/kangoo/6.jpg',
    nombre: 'TORNILLO DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Facil colocación.',
    precio: 52900,
  },
  {
    id: 7,
    imagen: './material/imagenes/kangoo/7.jpg',
    nombre: 'ENGANCHE BRACCO',
    descripcion1: 'Bastidor de caño 40×40 x3,2 de espesor y caños de 5/8 curvados.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Anclaje totalmente al chasis.',
    precio: 228800,
  },
  {
    id: 8,
    imagen: './material/imagenes/kangoo/8.jpg',
    nombre: 'CANASTO TECHO BRACCO',
    descripcion1: 'Caño de 1 pulgada x 1.6 de pared, las rejillas de 5/8 x 1.6.',
    descripcion2: 'Pintado negro con poliéster en polvo.',
    descripcion3: 'Anclajes directamente a los orificios de techo originales',
    precio: 258000,
  },
  {
    id: 9,
    imagen: './material/imagenes/kangoo/9.jpg',
    nombre: 'CHAPON CUBRECARTER BRACCO',
    descripcion1: 'Construidos en chapa acero al carbono 2 mm de espesor.',
    descripcion2: 'Otorga protección completa para el cárter del vehículo.',
    descripcion3: 'Pintados negro con poliéster en polvo.',
    precio: 109200,
  },
  {
    id: 10,
    imagen: './material/imagenes/kangoo/10.jpg',
    nombre: 'COBERTOR FURGON BRACCO',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Textura antideslizante de fácil limpieza.',
    descripcion3: 'Cubre piso furgón completo y alojamiento interior ruedas',
    precio: 302100,
  },
  {
    id: 11,
    imagen: './material/imagenes/kangoo/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 70400,
  },
  {
    id: 12,
    imagen: './material/imagenes/kangoo/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 71300,
  }
]
const articulosOroch = [
  {
    id: 1,
    imagen: './material/imagenes/oroch/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 320600,
  },
  {
    id: 2,
    imagen: './material/imagenes/oroch/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Punteras plásticas en las barras para no dañar la carga.',
    precio: 196200,
  },
  {
    id: 3,
    imagen: './material/imagenes/oroch/3.jpg',
    nombre: 'BARRA SAN ANTONIO',
    descripcion1: 'Compatible con lona marítima.',
    descripcion2: 'Ayuda a transportar cargas y objetos.',
    descripcion3: 'Cuenta con protector de luneta.',
    precio: 680300,
  },
  {
    id: 4,
    imagen: './material/imagenes/oroch/4.jpg',
    nombre: 'KIT BARREROS',
    descripcion1: 'Kit de barreros para las 4 ruedas.',
    descripcion2: 'Protege parte baja de vehículo de proyecciones de piedras.',
    descripcion3: 'Evita suciedad en carrocería por barro.',
    precio: 110000,
  },
  {
    id: 5,
    imagen: './material/imagenes/oroch/5.jpg',
    nombre: 'LONA MARITIMA',
    descripcion1: 'Manija apertura con cable de acero.',
    descripcion2: 'Cierre con resorte.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 423000,
  },
  {
    id: 6,
    imagen: './material/imagenes/oroch/6.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 68800,
  },
  {
    id: 7,
    imagen: './material/imagenes/oroch/7.jpg',
    nombre: 'ESTRIBOS',
    descripcion1: 'Perfil de aluminio estrusado con tratamiento anodizado natural.',
    descripcion2: 'Pisaderas antideslizantes y punteras de inyección plástica.',
    descripcion3: 'Fijados al chasis.',
    precio: 458200,
  },
  {
    id: 8,
    imagen: './material/imagenes/oroch/8.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 174700,
  },
  {
    id: 9,
    imagen: './material/imagenes/oroch/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 174500,
  },
  {
    id: 10,
    imagen: './material/imagenes/oroch/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 47600,
  },
  {
    id: 11,
    imagen: './material/imagenes/oroch/11.jpg',
    nombre: 'POLARIZADO',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 69800,
  },
  {
    id: 12,
    imagen: './material/imagenes/oroch/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 71300,
  },
  {
    id: 13,
    imagen: './material/imagenes/oroch/13.jpg',
    nombre: 'CAMARA DE RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 131100,
  }
]
const articulosSandero = [
  {
    id: 1,
    imagen: './material/imagenes/sandero/1.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 174500,
  },
  {
    id: 2,
    imagen: './material/imagenes/sandero/2.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 52900,
  },
  {
    id: 3,
    imagen: './material/imagenes/sandero/3.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 69800,
  },
  {
    id: 4,
    imagen: './material/imagenes/sandero/4.jpg',
    nombre: 'KIT DE SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 71300,
  },
  {
    id: 5,
    imagen: './material/imagenes/sandero/6.jpg',
    nombre: 'CHAPON CUBRECARTER',
    descripcion1: 'Construidos en chapa acero al carbono 2 mm de espesor.',
    descripcion2: 'Otorga protección completa para el cárter del vehículo.',
    descripcion3: 'Pintados negro con poliéster en polvo.',
    precio: 82000,
  }
]
const articulosStepway = [
  {
    id: 1,
    imagen: './material/imagenes/sandero/1.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 174500,
  },
  {
    id: 2,
    imagen: './material/imagenes/sandero/2.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 52900,
  },
  {
    id: 3,
    imagen: './material/imagenes/sandero/3.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 69800,
  },
  {
    id: 4,
    imagen: './material/imagenes/sandero/4.jpg',
    nombre: 'KIT DE SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 71300,
  },
  {
    id: 5,
    imagen: './material/imagenes/sandero/6.jpg',
    nombre: 'CHAPON CUBRECARTER',
    descripcion1: 'Construidos en chapa acero al carbono 2 mm de espesor.',
    descripcion2: 'Otorga protección completa para el cárter del vehículo.',
    descripcion3: 'Pintados negro con poliéster en polvo.',
    precio: 82000,
  },
  {
    id: 6,
    imagen: './material/imagenes/sandero/7.jpg',
    nombre: 'PORTA EQUIPAJE BRACCO',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Punteras plásticas en las barras para no dañar la carga.',
    precio: 173200,
  }
]
const articulosAlaskan = [
  {
    id: 1,
    imagen: './material/imagenes/alaskan/1.jpg',
    nombre: 'JAULA NEGRA',
    descripcion1: 'Jaula negra caño tubular simple',
    descripcion2: 'Base para lona marítima.',
    descripcion3: 'Bulonería con tratamiento anticorrosión.',
    precio: 472300,
  },
  {
    id: 2,
    imagen: './material/imagenes/alaskan/2.jpg',
    nombre: 'JAULA CROMADA',
    descripcion1: 'Jaula cromada caño tubular simple.',
    descripcion2: 'Base para lona marítima.',
    descripcion3: 'Bulonería con tratamiento anticorrosión.',
    precio: 655900,
  },
  {
    id: 3,
    imagen: './material/imagenes/alaskan/3.jpg',
    nombre: 'LONA MARITIMA',
    descripcion1: 'Manija apertura con cable de acero.',
    descripcion2: 'Cierre con resorte.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 332500,
  },
  {
    id: 4,
    imagen: './material/imagenes/alaskan/4.jpg',
    nombre: 'COBERTOR',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Textura antideslizante de fácil limpieza.',
    descripcion3: 'Forma perfectamente adaptada a caja.',
    precio: 303200,
  },
  {
    id: 5,
    imagen: './material/imagenes/alaskan/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 122800,
  },
  {
    id: 6,
    imagen: './material/imagenes/alaskan/6.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 688700,
  },
  {
    id: 7,
    imagen: './material/imagenes/alaskan/7.jpg',
    nombre: 'PROTECCION FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería  en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 348900,
  },
  {
    id: 8,
    imagen: './material/imagenes/alaskan/8.jpg',
    nombre: 'TUERCAS DE SEGURIDAD',
    descripcion1: 'Kit 4 tuercas de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil  colocación.',
    precio: 103700,
  },
  {
    id: 9,
    imagen: './material/imagenes/alaskan/9.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 69800,
  },
  {
    id: 10,
    imagen: './material/imagenes/alaskan/10.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 174500,
  },
  {
    id: 11,
    imagen: './material/imagenes/alaskan/11.jpg',
    nombre: 'TALAMPAYA INOXIDABLE BRACCO',
    descripcion1: 'Estructura de caño en una sola pieza acero inoxidable.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'No sobrepasa la línea del paragolpes.',
    precio: 315300,
  },
  {
    id: 12,
    imagen: './material/imagenes/alaskan/12.jpg',
    nombre: 'TALAMPAYA NEGRA BRACCO',
    descripcion1: 'Estructura de caño en una sola pieza.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'No sobrepasa la línea del paragolpes.',
    precio: 219000,
  },
  {
    id: 13,
    imagen: './material/imagenes/alaskan/13.jpg',
    nombre: 'ENGANCHE REFORZADO BRACCO',
    descripcion1: 'Bastidor de caño 60×60 x3,2 de espesor.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Anclaje totalmente al chasis.',
    precio: 297000,
  },
  {
    id: 14,
    imagen: './material/imagenes/alaskan/14.jpg',
    nombre: 'ENGANCHE COMUN BRACCO',
    descripcion1: 'Bastidor de caño 40×40 x3,2 de espesor.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Anclaje totalmente al chasis.',
    precio: 230000,
  },
  {
    id: 15,
    imagen: './material/imagenes/alaskan/15.jpg',
    nombre: 'JAULA CAÑO DOBLE INOXIDABLE BRACCO',
    descripcion1: 'Tubos de acero inoxidable.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 518300,
  },
  {
    id: 16,
    imagen: './material/imagenes/alaskan/16.jpg',
    nombre: 'JAULA CAÑO DOBLE NEGRA BRACCO',
    descripcion1: 'Tubos de acero al carbono.',
    descripcion2: 'Pintada negra con poliéster en polvo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 347000,
  },
  {
    id: 17,
    imagen: './material/imagenes/alaskan/17.jpg',
    nombre: 'JAULA CAÑO SIMPLE INOXIDABLE BRACCO',
    descripcion1: 'Tubos de acero inoxidable.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 341700,
  },
  {
    id: 18,
    imagen: './material/imagenes/alaskan/18.jpg',
    nombre: 'JAULA CAÑO SIMPLE NEGRA BRACCO',
    descripcion1: 'Tubos de acero al carbono.',
    descripcion2: 'Pintada negra con poliéster en polvo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 310700,
  },
  {
    id: 19,
    imagen: './material/imagenes/alaskan/19.jpg',
    nombre: 'JAULA TRABAJO BRACCO',
    descripcion1: 'Jaula despiezada para fácil trasporte.',
    descripcion2: 'Tubos de acero al carbono.',
    descripcion3: 'Pintada negra con poliéster en polvo.',
    precio: 397100,
  },
  {
    id: 20,
    imagen: './material/imagenes/alaskan/20.jpg',
    nombre: 'ESTRIBOS SIMIL ORIGINAL',
    descripcion1: 'Perfil de aluminio estrusado con tratamiento anodizado natural.',
    descripcion2: 'Pisaderas antideslizantes y punteras de inyección plástica.',
    descripcion3: 'Fijados al chasis.',
    precio: 408800,
  },
  {
    id: 21,
    imagen: './material/imagenes/alaskan/21.jpg',
    nombre: 'TAPA RIGIDA',
    descripcion1: 'Componentes ensamblados y sellados con siliconas especiales.',
    descripcion2: 'Resistente a las inclemencias del tiempo.',
    descripcion3: 'Fácil de operar en el uso diario.',
    precio: 783400,
  },
  {
    id: 22,
    imagen: './material/imagenes/alaskan/22.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 71300,
  }
]
const articulos208 = [
  {
    id: 1,
    imagen: './material/imagenes/duster/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 420200,
  },
  {
    id: 2,
    imagen: './material/imagenes/duster/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Cuenta con tapas plásticas para no dañar la carga.',
    precio: 131200,
  },
  {
    id: 3,
    imagen: './material/imagenes/duster/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 181400,
  },
  {
    id: 4,
    imagen: './material/imagenes/duster/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Protege y decora el vehículo.',
    descripcion2: 'Gran resistencia.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 135000,
  },
  {
    id: 5,
    imagen: './material/imagenes/duster/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 52700,
  },
  {
    id: 6,
    imagen: './material/imagenes/duster/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Listo para instalar.',
    descripcion2: 'Bloquea el acceso de herramientas genéricas.',
    descripcion3: 'Bloqueo del malacate de la rueda de auxilio.',
    precio: 10500,
  },
  {
    id: 7,
    imagen: './material/imagenes/duster/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 126500,
  },
  {
    id: 8,
    imagen: './material/imagenes/duster/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 107200,
  },
  {
    id: 9,
    imagen: './material/imagenes/duster/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 139500,
  },
  {
    id: 10,
    imagen: './material/imagenes/duster/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 41800,
  },
  {
    id: 11,
    imagen: './material/imagenes/duster/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 59800,
  },
  {
    id: 12,
    imagen: './material/imagenes/duster/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 54800,
  }
]
const articulos3008 = [
  {
    id: 1,
    imagen: './material/imagenes/duster/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 420200,
  },
  {
    id: 2,
    imagen: './material/imagenes/duster/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Cuenta con tapas plásticas para no dañar la carga.',
    precio: 131200,
  },
  {
    id: 3,
    imagen: './material/imagenes/duster/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 181400,
  },
  {
    id: 4,
    imagen: './material/imagenes/duster/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Protege y decora el vehículo.',
    descripcion2: 'Gran resistencia.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 135000,
  },
  {
    id: 5,
    imagen: './material/imagenes/duster/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 52700,
  },
  {
    id: 6,
    imagen: './material/imagenes/duster/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Listo para instalar.',
    descripcion2: 'Bloquea el acceso de herramientas genéricas.',
    descripcion3: 'Bloqueo del malacate de la rueda de auxilio.',
    precio: 10500,
  },
  {
    id: 7,
    imagen: './material/imagenes/duster/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 126500,
  },
  {
    id: 8,
    imagen: './material/imagenes/duster/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 107200,
  },
  {
    id: 9,
    imagen: './material/imagenes/duster/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 139500,
  },
  {
    id: 10,
    imagen: './material/imagenes/duster/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 41800,
  },
  {
    id: 11,
    imagen: './material/imagenes/duster/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 59800,
  },
  {
    id: 12,
    imagen: './material/imagenes/duster/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 54800,
  }
]
const articulos5008 = [
  {
    id: 1,
    imagen: './material/imagenes/duster/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 420200,
  },
  {
    id: 2,
    imagen: './material/imagenes/duster/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Cuenta con tapas plásticas para no dañar la carga.',
    precio: 131200,
  },
  {
    id: 3,
    imagen: './material/imagenes/duster/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 181400,
  },
  {
    id: 4,
    imagen: './material/imagenes/duster/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Protege y decora el vehículo.',
    descripcion2: 'Gran resistencia.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 135000,
  },
  {
    id: 5,
    imagen: './material/imagenes/duster/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 52700,
  },
  {
    id: 6,
    imagen: './material/imagenes/duster/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Listo para instalar.',
    descripcion2: 'Bloquea el acceso de herramientas genéricas.',
    descripcion3: 'Bloqueo del malacate de la rueda de auxilio.',
    precio: 10500,
  },
  {
    id: 7,
    imagen: './material/imagenes/duster/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 126500,
  },
  {
    id: 8,
    imagen: './material/imagenes/duster/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 107200,
  },
  {
    id: 9,
    imagen: './material/imagenes/duster/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 139500,
  },
  {
    id: 10,
    imagen: './material/imagenes/duster/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 41800,
  },
  {
    id: 11,
    imagen: './material/imagenes/duster/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 59800,
  },
  {
    id: 12,
    imagen: './material/imagenes/duster/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 54800,
  }
]
const articulosPartner = [
  {
    id: 1,
    imagen: './material/imagenes/duster/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 420200,
  },
  {
    id: 2,
    imagen: './material/imagenes/duster/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Cuenta con tapas plásticas para no dañar la carga.',
    precio: 131200,
  },
  {
    id: 3,
    imagen: './material/imagenes/duster/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 181400,
  },
  {
    id: 4,
    imagen: './material/imagenes/duster/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Protege y decora el vehículo.',
    descripcion2: 'Gran resistencia.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 135000,
  },
  {
    id: 5,
    imagen: './material/imagenes/duster/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 52700,
  },
  {
    id: 6,
    imagen: './material/imagenes/duster/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Listo para instalar.',
    descripcion2: 'Bloquea el acceso de herramientas genéricas.',
    descripcion3: 'Bloqueo del malacate de la rueda de auxilio.',
    precio: 10500,
  },
  {
    id: 7,
    imagen: './material/imagenes/duster/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 126500,
  },
  {
    id: 8,
    imagen: './material/imagenes/duster/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 107200,
  },
  {
    id: 9,
    imagen: './material/imagenes/duster/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 139500,
  },
  {
    id: 10,
    imagen: './material/imagenes/duster/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 41800,
  },
  {
    id: 11,
    imagen: './material/imagenes/duster/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 59800,
  },
  {
    id: 12,
    imagen: './material/imagenes/duster/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 54800,
  }
]
const articulosExpert = [
  {
    id: 1,
    imagen: './material/imagenes/duster/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 420200,
  },
  {
    id: 2,
    imagen: './material/imagenes/duster/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Cuenta con tapas plásticas para no dañar la carga.',
    precio: 131200,
  },
  {
    id: 3,
    imagen: './material/imagenes/duster/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 181400,
  },
  {
    id: 4,
    imagen: './material/imagenes/duster/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Protege y decora el vehículo.',
    descripcion2: 'Gran resistencia.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 135000,
  },
  {
    id: 5,
    imagen: './material/imagenes/duster/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 52700,
  },
  {
    id: 6,
    imagen: './material/imagenes/duster/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Listo para instalar.',
    descripcion2: 'Bloquea el acceso de herramientas genéricas.',
    descripcion3: 'Bloqueo del malacate de la rueda de auxilio.',
    precio: 10500,
  },
  {
    id: 7,
    imagen: './material/imagenes/duster/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 126500,
  },
  {
    id: 8,
    imagen: './material/imagenes/duster/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 107200,
  },
  {
    id: 9,
    imagen: './material/imagenes/duster/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 139500,
  },
  {
    id: 10,
    imagen: './material/imagenes/duster/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 41800,
  },
  {
    id: 11,
    imagen: './material/imagenes/duster/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 59800,
  },
  {
    id: 12,
    imagen: './material/imagenes/duster/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 54800,
  }
]
const articulosBoxer = [
  {
    id: 1,
    imagen: './material/imagenes/duster/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 420200,
  },
  {
    id: 2,
    imagen: './material/imagenes/duster/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Cuenta con tapas plásticas para no dañar la carga.',
    precio: 131200,
  },
  {
    id: 3,
    imagen: './material/imagenes/duster/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 181400,
  },
  {
    id: 4,
    imagen: './material/imagenes/duster/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Protege y decora el vehículo.',
    descripcion2: 'Gran resistencia.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 135000,
  },
  {
    id: 5,
    imagen: './material/imagenes/duster/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 52700,
  },
  {
    id: 6,
    imagen: './material/imagenes/duster/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Listo para instalar.',
    descripcion2: 'Bloquea el acceso de herramientas genéricas.',
    descripcion3: 'Bloqueo del malacate de la rueda de auxilio.',
    precio: 10500,
  },
  {
    id: 7,
    imagen: './material/imagenes/duster/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 126500,
  },
  {
    id: 8,
    imagen: './material/imagenes/duster/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 107200,
  },
  {
    id: 9,
    imagen: './material/imagenes/duster/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 139500,
  },
  {
    id: 10,
    imagen: './material/imagenes/duster/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 41800,
  },
  {
    id: 11,
    imagen: './material/imagenes/duster/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 59800,
  },
  {
    id: 12,
    imagen: './material/imagenes/duster/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 54800,
  }
]
=======
const articulosDuster = [
  {
    id: 1,
    imagen: './material/imagenes/duster/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 346300,
  },
  {
    id: 2,
    imagen: './material/imagenes/duster/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Cuenta con tapas plásticas para no dañar la carga.',
    precio: 105000,
  },
  {
    id: 3,
    imagen: './material/imagenes/duster/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 150100,
  },
  {
    id: 4,
    imagen: './material/imagenes/duster/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Protege y decora el vehículo.',
    descripcion2: 'Gran resistencia.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 111800,
  },
  {
    id: 5,
    imagen: './material/imagenes/duster/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 43400,
  },
  {
    id: 6,
    imagen: './material/imagenes/duster/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Listo para instalar.',
    descripcion2: 'Bloquea el acceso de herramientas genéricas.',
    descripcion3: 'Bloqueo del malacate de la rueda de auxilio.',
    precio: 10500,
  },
  {
    id: 7,
    imagen: './material/imagenes/duster/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 106200,
  },
  {
    id: 8,
    imagen: './material/imagenes/duster/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 93300,
  },
  {
    id: 9,
    imagen: './material/imagenes/duster/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 117900,
  },
  {
    id: 10,
    imagen: './material/imagenes/duster/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 34700,
  },
  {
    id: 11,
    imagen: './material/imagenes/duster/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 55500,
  },
  {
    id: 12,
    imagen: './material/imagenes/duster/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 43900,
  }
]
const articulosKangoo = [
  {
    id: 1,
    imagen: './material/imagenes/kangoo/1.jpg',
    nombre: 'CANASTO TECHO',
    descripcion1: 'Cubre totalmente el techo.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Peso máximo soportado 90 Kg.',
    precio: 519400,
  },
  {
    id: 2,
    imagen: './material/imagenes/kangoo/2.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 204400,
  },
  {
    id: 3,
    imagen: './material/imagenes/kangoo/3.jpg',
    nombre: 'CAMARA DE RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 93200,
  },
  {
    id: 4,
    imagen: './material/imagenes/kangoo/4.jpg',
    nombre: 'LLANTAS DE ALEACIÓN',
    descripcion1: 'Ancho 15.25 Cm.',
    descripcion2: 'Diámetro de la llanta 15 pulgadas.',
    descripcion3: 'Material Aleación de aluminio.',
    precio: 386100,
  },
  {
    id: 5,
    imagen: './material/imagenes/kangoo/5.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 117900,
  },
  {
    id: 6,
    imagen: './material/imagenes/kangoo/6.jpg',
    nombre: 'TORNILLO DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Facil colocación.',
    precio: 34700,
  },
  {
    id: 7,
    imagen: './material/imagenes/kangoo/7.jpg',
    nombre: 'ENGANCHE BRACCO',
    descripcion1: 'Bastidor de caño 40×40 x3,2 de espesor y caños de 5/8 curvados.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Anclaje totalmente al chasis.',
    precio: 182700,
  },
  {
    id: 8,
    imagen: './material/imagenes/kangoo/8.jpg',
    nombre: 'CANASTO TECHO BRACCO',
    descripcion1: 'Caño de 1 pulgada x 1.6 de pared, las rejillas de 5/8 x 1.6.',
    descripcion2: 'Pintado negro con poliéster en polvo.',
    descripcion3: 'Anclajes directamente a los orificios de techo originales',
    precio: 208500,
  },
  {
    id: 9,
    imagen: './material/imagenes/kangoo/9.jpg',
    nombre: 'CHAPON CUBRECARTER BRACCO',
    descripcion1: 'Construidos en chapa acero al carbono 2 mm de espesor.',
    descripcion2: 'Otorga protección completa para el cárter del vehículo.',
    descripcion3: 'Pintados negro con poliéster en polvo.',
    precio: 88500,
  },
  {
    id: 10,
    imagen: './material/imagenes/kangoo/10.jpg',
    nombre: 'COBERTOR FURGON BRACCO',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Textura antideslizante de fácil limpieza.',
    descripcion3: 'Cubre piso furgón completo y alojamiento interior ruedas',
    precio: 202500,
  },
  {
    id: 11,
    imagen: './material/imagenes/kangoo/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 53456,
  },
  {
    id: 12,
    imagen: './material/imagenes/kangoo/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 55500,
  }
]
const articulosOroch = [
  {
    id: 1,
    imagen: './material/imagenes/oroch/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 205700,
  },
  {
    id: 2,
    imagen: './material/imagenes/oroch/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Punteras plásticas en las barras para no dañar la carga.',
    precio: 122900,
  },
  {
    id: 3,
    imagen: './material/imagenes/oroch/3.jpg',
    nombre: 'BARRA SAN ANTONIO',
    descripcion1: 'Compatible con lona marítima.',
    descripcion2: 'Ayuda a transportar cargas y objetos.',
    descripcion3: 'Cuenta con protector de luneta.',
    precio: 427000,
  },
  {
    id: 4,
    imagen: './material/imagenes/oroch/4.jpg',
    nombre: 'KIT BARREROS',
    descripcion1: 'Kit de barreros para las 4 ruedas.',
    descripcion2: 'Protege parte baja de vehículo de proyecciones de piedras.',
    descripcion3: 'Evita suciedad en carrocería por barro.',
    precio: 72000,
  },
  {
    id: 5,
    imagen: './material/imagenes/oroch/5.jpg',
    nombre: 'LONA MARITIMA',
    descripcion1: 'Manija apertura con cable de acero.',
    descripcion2: 'Cierre con resorte.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 264500,
  },
  {
    id: 6,
    imagen: './material/imagenes/oroch/6.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 46500,
  },
  {
    id: 7,
    imagen: './material/imagenes/oroch/7.jpg',
    nombre: 'ESTRIBOS',
    descripcion1: 'Perfil de aluminio estrusado con tratamiento anodizado natural.',
    descripcion2: 'Pisaderas antideslizantes y punteras de inyección plástica.',
    descripcion3: 'Fijados al chasis.',
    precio: 288300,
  },
  {
    id: 8,
    imagen: './material/imagenes/oroch/8.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 115900,
  },
  {
    id: 9,
    imagen: './material/imagenes/oroch/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 117900,
  },
  {
    id: 10,
    imagen: './material/imagenes/oroch/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 30600,
  },
  {
    id: 11,
    imagen: './material/imagenes/oroch/11.jpg',
    nombre: 'POLARIZADO',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 54800,
  },
  {
    id: 12,
    imagen: './material/imagenes/oroch/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 43900,
  },
  {
    id: 13,
    imagen: './material/imagenes/oroch/13.jpg',
    nombre: 'CAMARA DE RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 93200,
  }
]
const articulosSandero = [
  {
    id: 1,
    imagen: './material/imagenes/sandero/1.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 117900,
  },
  {
    id: 2,
    imagen: './material/imagenes/sandero/2.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 34700,
  },
  {
    id: 3,
    imagen: './material/imagenes/sandero/3.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 55500,
  },
  {
    id: 4,
    imagen: './material/imagenes/sandero/4.jpg',
    nombre: 'KIT DE SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 43900,
  },
  {
    id: 5,
    imagen: './material/imagenes/sandero/5.jpg',
    nombre: 'CAMARA DE RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 1234,
  },
  {
    id: 6,
    imagen: './material/imagenes/sandero/6.jpg',
    nombre: 'CHAPON CUBRECARTER',
    descripcion1: 'Construidos en chapa acero al carbono 2 mm de espesor.',
    descripcion2: 'Otorga protección completa para el cárter del vehículo.',
    descripcion3: 'Pintados negro con poliéster en polvo.',
    precio: 93300,
  }
]
const articulosStepway = [
  {
    id: 1,
    imagen: './material/imagenes/sandero/1.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 117900,
  },
  {
    id: 2,
    imagen: './material/imagenes/sandero/2.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 34700,
  },
  {
    id: 3,
    imagen: './material/imagenes/sandero/3.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 55500,
  },
  {
    id: 4,
    imagen: './material/imagenes/sandero/4.jpg',
    nombre: 'KIT DE SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 43900,
  },
  {
    id: 5,
    imagen: './material/imagenes/sandero/5.jpg',
    nombre: 'CAMARA DE RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 93300,
  },
  {
    id: 6,
    imagen: './material/imagenes/sandero/6.jpg',
    nombre: 'CHAPON CUBRECARTER',
    descripcion1: 'Construidos en chapa acero al carbono 2 mm de espesor.',
    descripcion2: 'Otorga protección completa para el cárter del vehículo.',
    descripcion3: 'Pintados negro con poliéster en polvo.',
    precio: 66900,
  },
  {
    id: 5,
    imagen: './material/imagenes/sandero/7.jpg',
    nombre: 'PORTA EQUIPAJE BRACCO',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Punteras plásticas en las barras para no dañar la carga.',
    precio: 141000,
  }
]
const articulosAlaskan = [
  {
    id: 1,
    imagen: './material/imagenes/alaskan/1.jpg',
    nombre: 'JAULA NEGRA',
    descripcion1: 'Jaula negra caño tubular simple',
    descripcion2: 'Base para lona marítima.',
    descripcion3: 'Bulonería con tratamiento anticorrosión.',
    precio: 299000,
  },
  {
    id: 2,
    imagen: './material/imagenes/alaskan/2.jpg',
    nombre: 'JAULA CROMADA',
    descripcion1: 'Jaula cromada caño tubular simple.',
    descripcion2: 'Base para lona marítima.',
    descripcion3: 'Bulonería con tratamiento anticorrosión.',
    precio: 412000,
  },
  {
    id: 3,
    imagen: './material/imagenes/alaskan/3.jpg',
    nombre: 'LONA MARITIMA',
    descripcion1: 'Manija apertura con cable de acero.',
    descripcion2: 'Cierre con resorte.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 210900,
  },
  {
    id: 4,
    imagen: './material/imagenes/alaskan/4.jpg',
    nombre: 'COBERTOR',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Textura antideslizante de fácil limpieza.',
    descripcion3: 'Forma perfectamente adaptada a caja.',
    precio: 201500,
  },
  {
    id: 5,
    imagen: './material/imagenes/alaskan/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 79800,
  },
  {
    id: 6,
    imagen: './material/imagenes/alaskan/6.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 440600,
  },
  {
    id: 7,
    imagen: './material/imagenes/alaskan/7.jpg',
    nombre: 'PROTECCION FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería  en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 218900,
  },
  {
    id: 8,
    imagen: './material/imagenes/alaskan/8.jpg',
    nombre: 'TUERCAS DE SEGURIDAD',
    descripcion1: 'Kit 4 tuercas de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil  colocación.',
    precio: 65100,
  },
  {
    id: 9,
    imagen: './material/imagenes/alaskan/9.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 55500,
  },
  {
    id: 10,
    imagen: './material/imagenes/alaskan/10.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 117900,
  },
  {
    id: 11,
    imagen: './material/imagenes/alaskan/11.jpg',
    nombre: 'TALAMPAYA INOXIDABLE BRACCO',
    descripcion1: 'Estructura de caño en una sola pieza acero inoxidable.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'No sobrepasa la línea del paragolpes.',
    precio: 252300,
  },
  {
    id: 12,
    imagen: './material/imagenes/alaskan/12.jpg',
    nombre: 'TALAMPAYA NEGRA BRACCO',
    descripcion1: 'Estructura de caño en una sola pieza.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'No sobrepasa la línea del paragolpes.',
    precio: 176600,
  },
  {
    id: 13,
    imagen: './material/imagenes/alaskan/13.jpg',
    nombre: 'ENGANCHE REFORZADO BRACCO',
    descripcion1: 'Bastidor de caño 60×60 x3,2 de espesor.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Anclaje totalmente al chasis.',
    precio: 237600,
  },
  {
    id: 14,
    imagen: './material/imagenes/alaskan/14.jpg',
    nombre: 'ENGANCHE COMUN BRACCO',
    descripcion1: 'Bastidor de caño 40×40 x3,2 de espesor.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Anclaje totalmente al chasis.',
    precio: 195800,
  },
  {
    id: 15,
    imagen: './material/imagenes/alaskan/15.jpg',
    nombre: 'JAULA CAÑO DOBLE INOXIDABLE BRACCO',
    descripcion1: 'Tubos de acero inoxidable.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 414600,
  },
  {
    id: 16,
    imagen: './material/imagenes/alaskan/16.jpg',
    nombre: 'JAULA CAÑO DOBLE NEGRA BRACCO',
    descripcion1: 'Tubos de acero al carbono.',
    descripcion2: 'Pintada negra con poliéster en polvo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 277600,
  },
  {
    id: 17,
    imagen: './material/imagenes/alaskan/17.jpg',
    nombre: 'JAULA CAÑO SIMPLE INOXIDABLE BRACCO',
    descripcion1: 'Tubos de acero inoxidable.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 321400,
  },
  {
    id: 18,
    imagen: './material/imagenes/alaskan/18.jpg',
    nombre: 'JAULA CAÑO SIMPLE NEGRA BRACCO',
    descripcion1: 'Tubos de acero al carbono.',
    descripcion2: 'Pintada negra con poliéster en polvo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 248600,
  },
  {
    id: 19,
    imagen: './material/imagenes/alaskan/19.jpg',
    nombre: 'JAULA TRABAJO BRACCO',
    descripcion1: 'Jaula despiezada para fácil trasporte.',
    descripcion2: 'Tubos de acero al carbono.',
    descripcion3: 'Pintada negra con poliéster en polvo.',
    precio: 317700,
  },
  {
    id: 20,
    imagen: './material/imagenes/alaskan/20.jpg',
    nombre: 'ESTRIBOS SIMIL ORIGINAL',
    descripcion1: 'Perfil de aluminio estrusado con tratamiento anodizado natural.',
    descripcion2: 'Pisaderas antideslizantes y punteras de inyección plástica.',
    descripcion3: 'Fijados al chasis.',
    precio: 334500,
  },
  {
    id: 21,
    imagen: './material/imagenes/alaskan/21.jpg',
    nombre: 'TAPA RIGIDA',
    descripcion1: 'Componentes ensamblados y sellados con siliconas especiales.',
    descripcion2: 'Resistente a las inclemencias del tiempo.',
    descripcion3: 'Fácil de operar en el uso diario.',
    precio: 628200,
  },
  {
    id: 22,
    imagen: './material/imagenes/alaskan/22.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 43900,
  }
]
>>>>>>> 5eec35e26e787a2d3facb4f277e38d8b16e86114
