const articulosDuster = [
  {
    id: 1,
    imagen: './material/imagenes/duster/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 608100,
  },
  {
    id: 2,
    imagen: './material/imagenes/duster/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Cuenta con tapas plásticas para no dañar la carga.',
    precio: 199500,
  },
  {
    id: 3,
    imagen: './material/imagenes/duster/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 257500,
  },
  {
    id: 4,
    imagen: './material/imagenes/duster/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Protege y decora el vehículo.',
    descripcion2: 'Gran resistencia.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 171400,
  },
  {
    id: 5,
    imagen: './material/imagenes/duster/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 76300,
  },
  {
    id: 6,
    imagen: './material/imagenes/duster/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Listo para instalar.',
    descripcion2: 'Bloquea el acceso de herramientas genéricas.',
    descripcion3: 'Bloqueo del malacate de la rueda de auxilio.',
    precio: 25600,
  },
  {
    id: 7,
    imagen: './material/imagenes/duster/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 176900,
  },
  {
    id: 8,
    imagen: './material/imagenes/duster/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 139800,
  },
  {
    id: 9,
    imagen: './material/imagenes/duster/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 192900,
  },
  {
    id: 10,
    imagen: './material/imagenes/duster/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 59700,
  },
  {
    id: 11,
    imagen: './material/imagenes/duster/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 90100,
  },
  {
    id: 12,
    imagen: './material/imagenes/duster/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 83500,
  }
]
const articulosKangoo = [
  {
    id: 1,
    imagen: './material/imagenes/kangoo/1.jpg',
    nombre: 'CANASTO TECHO',
    descripcion1: 'Cubre totalmente el techo.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Peso máximo soportado 90 Kg.',
    precio: 962600,
  },
  {
    id: 2,
    imagen: './material/imagenes/kangoo/2.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 369800,
  },
  {
    id: 3,
    imagen: './material/imagenes/kangoo/3.jpg',
    nombre: 'CAMARA DE RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 139900,
  },
  {
    id: 4,
    imagen: './material/imagenes/kangoo/4.jpg',
    nombre: 'LLANTAS DE ALEACIÓN',
    descripcion1: 'Ancho 15.25 Cm.',
    descripcion2: 'Diámetro de la llanta 15 pulgadas.',
    descripcion3: 'Material Aleación de aluminio.',
    precio: 587700,
  },
  {
    id: 5,
    imagen: './material/imagenes/kangoo/5.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 192900,
  },
  {
    id: 6,
    imagen: './material/imagenes/kangoo/6.jpg',
    nombre: 'TORNILLO DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Facil colocación.',
    precio: 59700,
  },
  {
    id: 7,
    imagen: './material/imagenes/kangoo/7.jpg',
    nombre: 'ENGANCHE BRACCO',
    descripcion1: 'Bastidor de caño 40×40 x3,2 de espesor y caños de 5/8 curvados.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Anclaje totalmente al chasis.',
    precio: 247400,
  },
  {
    id: 8,
    imagen: './material/imagenes/kangoo/8.jpg',
    nombre: 'CANASTO TECHO BRACCO',
    descripcion1: 'Caño de 1 pulgada x 1.6 de pared, las rejillas de 5/8 x 1.6.',
    descripcion2: 'Pintado negro con poliéster en polvo.',
    descripcion3: 'Anclajes directamente a los orificios de techo originales',
    precio: 962600,
  },
  {
    id: 9,
    imagen: './material/imagenes/kangoo/9.jpg',
    nombre: 'CHAPON CUBRECARTER BRACCO',
    descripcion1: 'Construidos en chapa acero al carbono 2 mm de espesor.',
    descripcion2: 'Otorga protección completa para el cárter del vehículo.',
    descripcion3: 'Pintados negro con poliéster en polvo.',
    precio: 120500,
  },
  {
    id: 10,
    imagen: './material/imagenes/kangoo/10.jpg',
    nombre: 'COBERTOR FURGON BRACCO',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Textura antideslizante de fácil limpieza.',
    descripcion3: 'Cubre piso furgón completo y alojamiento interior ruedas',
    precio: 332700,
  },
  {
    id: 11,
    imagen: './material/imagenes/kangoo/11.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 90100,
  },
  {
    id: 12,
    imagen: './material/imagenes/kangoo/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 83500,
  }
]
const articulosOroch = [
  {
    id: 1,
    imagen: './material/imagenes/oroch/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 366100,
  },
  {
    id: 2,
    imagen: './material/imagenes/oroch/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Punteras plásticas en las barras para no dañar la carga.',
    precio: 227200,
  },
  {
    id: 3,
    imagen: './material/imagenes/oroch/3.jpg',
    nombre: 'BARRA SAN ANTONIO',
    descripcion1: 'Compatible con lona marítima.',
    descripcion2: 'Ayuda a transportar cargas y objetos.',
    descripcion3: 'Cuenta con protector de luneta.',
    precio: 786900,
  },
  {
    id: 4,
    imagen: './material/imagenes/oroch/4.jpg',
    nombre: 'KIT BARREROS',
    descripcion1: 'Kit de barreros para las 4 ruedas.',
    descripcion2: 'Protege parte baja de vehículo de proyecciones de piedras.',
    descripcion3: 'Evita suciedad en carrocería por barro.',
    precio: 124200,
  },
  {
    id: 5,
    imagen: './material/imagenes/oroch/5.jpg',
    nombre: 'LONA MARITIMA',
    descripcion1: 'Manija apertura con cable de acero.',
    descripcion2: 'Cierre con resorte.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 490400,
  },
  {
    id: 6,
    imagen: './material/imagenes/oroch/6.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 75900,
  },
  {
    id: 7,
    imagen: './material/imagenes/oroch/7.jpg',
    nombre: 'ESTRIBOS',
    descripcion1: 'Perfil de aluminio estrusado con tratamiento anodizado natural.',
    descripcion2: 'Pisaderas antideslizantes y punteras de inyección plástica.',
    descripcion3: 'Fijados al chasis.',
    precio: 529500,
  },
  {
    id: 8,
    imagen: './material/imagenes/oroch/8.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Plegable.',
    descripcion2: 'Baulera guardaobjetos.',
    descripcion3: 'Parte superior acolchada.',
    precio: 195500,
  },
  {
    id: 9,
    imagen: './material/imagenes/oroch/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 192900,
  },
  {
    id: 10,
    imagen: './material/imagenes/oroch/10.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 54400,
  },
  {
    id: 11,
    imagen: './material/imagenes/oroch/11.jpg',
    nombre: 'POLARIZADO',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 90100,
  },
  {
    id: 12,
    imagen: './material/imagenes/oroch/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 83500,
  },
  {
    id: 13,
    imagen: './material/imagenes/oroch/13.jpg',
    nombre: 'CAMARA DE RETROCESO',
    descripcion1: 'Cámara adaptada para vincular a MediaNav.',
    descripcion2: 'Línea de guía.',
    descripcion3: 'Brillo adaptable.',
    precio: 139900,
  }
]
const articulosSandero = [
  {
    id: 1,
    imagen: './material/imagenes/sandero/1.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 192900,
  },
  {
    id: 2,
    imagen: './material/imagenes/sandero/2.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 59700,
  },
  {
    id: 3,
    imagen: './material/imagenes/sandero/3.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 90100,
  },
  {
    id: 4,
    imagen: './material/imagenes/sandero/4.jpg',
    nombre: 'KIT DE SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 83500,
  },
  {
    id: 5,
    imagen: './material/imagenes/sandero/6.jpg',
    nombre: 'CHAPON CUBRECARTER',
    descripcion1: 'Construidos en chapa acero al carbono 2 mm de espesor.',
    descripcion2: 'Otorga protección completa para el cárter del vehículo.',
    descripcion3: 'Pintados negro con poliéster en polvo.',
    precio: 90000,
  }
]
const articulosStepway = [
  {
    id: 1,
    imagen: './material/imagenes/sandero/1.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 192900,
  },
  {
    id: 2,
    imagen: './material/imagenes/sandero/2.jpg',
    nombre: 'TORNILLOS DE SEGURIDAD',
    descripcion1: 'Kit 4 tornillos de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil colocación.',
    precio: 59700,
  },
  {
    id: 3,
    imagen: './material/imagenes/sandero/3.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 90100,
  },
  {
    id: 4,
    imagen: './material/imagenes/sandero/4.jpg',
    nombre: 'KIT DE SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 83500,
  },
  {
    id: 5,
    imagen: './material/imagenes/sandero/6.jpg',
    nombre: 'CHAPON CUBRECARTER',
    descripcion1: 'Construidos en chapa acero al carbono 2 mm de espesor.',
    descripcion2: 'Otorga protección completa para el cárter del vehículo.',
    descripcion3: 'Pintados negro con poliéster en polvo.',
    precio: 90000,
  },
  {
    id: 6,
    imagen: './material/imagenes/sandero/7.jpg',
    nombre: 'PORTA EQUIPAJE BRACCO',
    descripcion1: 'Fabricadas en hierro reforzado.',
    descripcion2: 'Fácil colocación, no requiere hacer modificaciones en el vehículo.',
    descripcion3: 'Punteras plásticas en las barras para no dañar la carga.',
    precio: 785200,
  }
]
const articulosAlaskan = [
  {
    id: 1,
    imagen: './material/imagenes/alaskan/1.jpg',
    nombre: 'JAULA NEGRA',
    descripcion1: 'Jaula negra caño tubular simple',
    descripcion2: 'Base para lona marítima.',
    descripcion3: 'Bulonería con tratamiento anticorrosión.',
    precio: 543500,
  },
  {
    id: 2,
    imagen: './material/imagenes/alaskan/2.jpg',
    nombre: 'JAULA CROMADA',
    descripcion1: 'Jaula cromada caño tubular simple.',
    descripcion2: 'Base para lona marítima.',
    descripcion3: 'Bulonería con tratamiento anticorrosión.',
    precio: 758400,
  },
  {
    id: 3,
    imagen: './material/imagenes/alaskan/3.jpg',
    nombre: 'LONA MARITIMA BRACCO',
    descripcion1: 'Manija apertura con cable de acero.',
    descripcion2: 'Cierre con resorte.',
    descripcion3: 'Grampa de fijación con bulón oculto.',
    precio: 306900,
  },
  {
    id: 4,
    imagen: './material/imagenes/alaskan/4.jpg',
    nombre: 'COBERTOR',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Textura antideslizante de fácil limpieza.',
    descripcion3: 'Forma perfectamente adaptada a caja.',
    precio: 335600,
  },
  {
    id: 5,
    imagen: './material/imagenes/alaskan/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Acrílico resistente',
    descripcion2: 'No permite formación de remolinos en interior del habitáculo.',
    descripcion3: 'Desvía entrada de aire protegiendo ocupantes.',
    precio: 139200,
  },
  {
    id: 6,
    imagen: './material/imagenes/alaskan/6.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Evita la aspersión de arena, barro y piedras.',
    descripcion2: 'Incluye kit limpiador de superficie para adhesivo.',
    descripcion3: 'Reduce daños en caso de accidentes menores',
    precio: 787700,
  },
  {
    id: 7,
    imagen: './material/imagenes/alaskan/7.jpg',
    nombre: 'PROTECCION FRONTAL',
    descripcion1: 'Plástico termoformado resistente al sol y productos químicos.',
    descripcion2: 'Protege carrocería  en caso de colisión menor.',
    descripcion3: 'Aspecto de robustez.',
    precio: 403700,
  },
  {
    id: 8,
    imagen: './material/imagenes/alaskan/8.jpg',
    nombre: 'TUERCAS DE SEGURIDAD',
    descripcion1: 'Kit 4 tuercas de seguridad con llave especial.',
    descripcion2: 'Evita la manipulación de llantas con herramientas convencionales.',
    descripcion3: 'Fácil  colocación.',
    precio: 120000,
  },
  {
    id: 9,
    imagen: './material/imagenes/alaskan/9.jpg',
    nombre: 'POLARIZADOS',
    descripcion1: 'Polarizados comunes y de seguridad.',
    descripcion2: 'Laminas con tonalidad media y clara.',
    descripcion3: 'Bloquea rayos UV protegiendo a pasajeros e interiores.',
    precio: 90100,
  },
  {
    id: 10,
    imagen: './material/imagenes/alaskan/10.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Alerta sonora al acercarse a un objeto.',
    descripcion2: 'Regulación de distancia de alerta.',
    descripcion3: 'Activa al colocar reversa.',
    precio: 192900,
  },
  {
    id: 11,
    imagen: './material/imagenes/alaskan/11.jpg',
    nombre: 'TALAMPAYA INOXIDABLE BRACCO',
    descripcion1: 'Estructura de caño en una sola pieza acero inoxidable.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'No sobrepasa la línea del paragolpes.',
    precio: 345900,
  },
  {
    id: 12,
    imagen: './material/imagenes/alaskan/12.jpg',
    nombre: 'TALAMPAYA NEGRA BRACCO',
    descripcion1: 'Estructura de caño en una sola pieza.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'No sobrepasa la línea del paragolpes.',
    precio: 237200,
  },
  {
    id: 13,
    imagen: './material/imagenes/alaskan/13.jpg',
    nombre: 'ENGANCHE REFORZADO BRACCO',
    descripcion1: 'Bastidor de caño 60×60 x3,2 de espesor.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Anclaje totalmente al chasis.',
    precio: 325400,
  },
  {
    id: 14,
    imagen: './material/imagenes/alaskan/14.jpg',
    nombre: 'ENGANCHE COMUN BRACCO',
    descripcion1: 'Bastidor de caño 40×40 x3,2 de espesor.',
    descripcion2: 'Pintados negro con poliéster en polvo.',
    descripcion3: 'Anclaje totalmente al chasis.',
    precio: 249300,
  },
  {
    id: 15,
    imagen: './material/imagenes/alaskan/15.jpg',
    nombre: 'JAULA CAÑO DOBLE INOXIDABLE BRACCO',
    descripcion1: 'Tubos de acero inoxidable.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 573300,
  },
  {
    id: 16,
    imagen: './material/imagenes/alaskan/16.jpg',
    nombre: 'JAULA CAÑO DOBLE NEGRA BRACCO',
    descripcion1: 'Tubos de acero al carbono.',
    descripcion2: 'Pintada negra con poliéster en polvo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 381400,
  },
  {
    id: 17,
    imagen: './material/imagenes/alaskan/17.jpg',
    nombre: 'JAULA CAÑO SIMPLE INOXIDABLE BRACCO',
    descripcion1: 'Tubos de acero inoxidable.',
    descripcion2: 'Terminación pulido espejo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 442800,
  },
  {
    id: 18,
    imagen: './material/imagenes/alaskan/18.jpg',
    nombre: 'JAULA CAÑO SIMPLE NEGRA BRACCO',
    descripcion1: 'Tubos de acero al carbono.',
    descripcion2: 'Pintada negra con poliéster en polvo.',
    descripcion3: 'Bases para todo tipo de lona.',
    precio: 340700,
  },
  {
    id: 19,
    imagen: './material/imagenes/alaskan/19.jpg',
    nombre: 'JAULA TRABAJO BRACCO',
    descripcion1: 'Jaula despiezada para fácil trasporte.',
    descripcion2: 'Tubos de acero al carbono.',
    descripcion3: 'Pintada negra con poliéster en polvo.',
    precio: 437600,
  },
  {
    id: 20,
    imagen: './material/imagenes/alaskan/20.jpg',
    nombre: 'ESTRIBOS SIMIL ORIGINAL',
    descripcion1: 'Perfil de aluminio estrusado con tratamiento anodizado natural.',
    descripcion2: 'Pisaderas antideslizantes y punteras de inyección plástica.',
    descripcion3: 'Fijados al chasis.',
    precio: 459600,
  },
  {
    id: 21,
    imagen: './material/imagenes/alaskan/21.jpg',
    nombre: 'TAPA RIGIDA',
    descripcion1: 'Componentes ensamblados y sellados con siliconas especiales.',
    descripcion2: 'Resistente a las inclemencias del tiempo.',
    descripcion3: 'Fácil de operar en el uso diario.',
    precio: 926700,
  },
  {
    id: 22,
    imagen: './material/imagenes/alaskan/22.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Matafuego homologado 1kg polvo ABC.',
    descripcion2: 'Balizas reflectivas con base.',
    descripcion3: 'Botiquín.',
    precio: 83500,
  }
]
