const articulosDuster = [
  {
    id: 1,
    imagen: './material/imagenes/duster/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 2,
    imagen: './material/imagenes/duster/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 3,
    imagen: './material/imagenes/duster/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 4,
    imagen: './material/imagenes/duster/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 5,
    imagen: './material/imagenes/duster/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 6,
    imagen: './material/imagenes/duster/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 7,
    imagen: './material/imagenes/duster/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 8,
    imagen: './material/imagenes/duster/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 9,
    imagen: './material/imagenes/duster/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 10,
    imagen: './material/imagenes/duster/10.jpg',
    nombre: 'TUERCAS DE SEGURIDAD',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 11,
    imagen: './material/imagenes/duster/11.jpg',
    nombre: 'POLARIZADO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 12,
    imagen: './material/imagenes/duster/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  }
]
const articulosKangoo = [
  {
    id: 1,
    imagen: './material/imagenes/kangoo/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 2,
    imagen: './material/imagenes/kangoo/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 3,
    imagen: './material/imagenes/kangoo/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 4,
    imagen: './material/imagenes/kangoo/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 5,
    imagen: './material/imagenes/kangoo/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 6,
    imagen: './material/imagenes/kangoo/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 7,
    imagen: './material/imagenes/kangoo/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 8,
    imagen: './material/imagenes/kangoo/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 9,
    imagen: './material/imagenes/kangoo/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 10,
    imagen: './material/imagenes/kangoo/10.jpg',
    nombre: 'TUERCAS DE SEGURIDAD',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 11,
    imagen: './material/imagenes/kangoo/11.jpg',
    nombre: 'POLARIZADO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 12,
    imagen: './material/imagenes/kangoo/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  }
]
const articulosOroch = [
  {
    id: 1,
    imagen: './material/imagenes/oroch/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 2,
    imagen: './material/imagenes/oroch/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 3,
    imagen: './material/imagenes/oroch/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 4,
    imagen: './material/imagenes/oroch/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 5,
    imagen: './material/imagenes/oroch/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 6,
    imagen: './material/imagenes/oroch/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 7,
    imagen: './material/imagenes/oroch/7.jpg',
    nombre: 'KIT FENDERS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 8,
    imagen: './material/imagenes/oroch/8.jpg',
    nombre: 'CAMARA RETROCESO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 9,
    imagen: './material/imagenes/oroch/9.jpg',
    nombre: 'SENSORES DE ESTACIONAMIENTO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 10,
    imagen: './material/imagenes/oroch/10.jpg',
    nombre: 'TUERCAS DE SEGURIDAD',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 11,
    imagen: './material/imagenes/oroch/11.jpg',
    nombre: 'POLARIZADO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 12,
    imagen: './material/imagenes/oroch/12.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 13,
    imagen: './material/imagenes/oroch/13.jpg',
    nombre: 'KIT SEGURIDAD',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  }
]
const articulosSandero = [
  {
    id: 1,
    imagen: './material/imagenes/sandero/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 2,
    imagen: './material/imagenes/sandero/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 3,
    imagen: './material/imagenes/sandero/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 4,
    imagen: './material/imagenes/sandero/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 5,
    imagen: './material/imagenes/sandero/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 6,
    imagen: './material/imagenes/sandero/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  }
]
const articulosStepway = [
  {
    id: 1,
    imagen: './material/imagenes/sandero/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 2,
    imagen: './material/imagenes/sandero/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 3,
    imagen: './material/imagenes/sandero/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 4,
    imagen: './material/imagenes/sandero/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 5,
    imagen: './material/imagenes/sandero/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 6,
    imagen: './material/imagenes/sandero/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 5,
    imagen: './material/imagenes/sandero/7.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  }
]
const articulosAlaskan = [
  {
    id: 1,
    imagen: './material/imagenes/alaskan/1.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 2,
    imagen: './material/imagenes/alaskan/2.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 3,
    imagen: './material/imagenes/alaskan/3.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 4,
    imagen: './material/imagenes/alaskan/4.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 5,
    imagen: './material/imagenes/alaskan/5.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 6,
    imagen: './material/imagenes/alaskan/6.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 7,
    imagen: './material/imagenes/alaskan/7.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 8,
    imagen: './material/imagenes/alaskan/8.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 9,
    imagen: './material/imagenes/alaskan/9.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 10,
    imagen: './material/imagenes/alaskan/10.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 11,
    imagen: './material/imagenes/alaskan/11.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 12,
    imagen: './material/imagenes/alaskan/12.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 13,
    imagen: './material/imagenes/alaskan/13.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 14,
    imagen: './material/imagenes/alaskan/14.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 15,
    imagen: './material/imagenes/alaskan/15.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 16,
    imagen: './material/imagenes/alaskan/16.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  },
  {
    id: 17,
    imagen: './material/imagenes/alaskan/17.jpg',
    nombre: 'PROTECTORES DE PUERTA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 89769,
  },
  {
    id: 18,
    imagen: './material/imagenes/alaskan/18.jpg',
    nombre: 'DEFLECTORES DE LLUVIA',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 19,
    imagen: './material/imagenes/alaskan/19.jpg',
    nombre: 'TRABA RUEDA AUXILIO',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 20,
    imagen: './material/imagenes/alaskan/20.jpg',
    nombre: 'DEFENSA FRONTAL',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 1234,
  },
  {
    id: 21,
    imagen: './material/imagenes/alaskan/21.jpg',
    nombre: 'PORTA EQUIPAJE',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 12312,
  },
  {
    id: 22,
    imagen: './material/imagenes/alaskan/22.jpg',
    nombre: 'APOYABRAZOS',
    descripcion1: 'Jaula caño tubular simple',
    descripcion2: 'Jaula caño tubular simple',
    descripcion3: 'Jaula caño tubular simple',
    precio: 53456,
  }
]